# Generated by Django 2.2 on 2020-09-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='fecha_mod',
            new_name='date_mod',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='fecha_pub',
            new_name='date_pub',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='votos_minus',
            new_name='votes_minus',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='votos_plus',
            new_name='votes_plus',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_mod',
            new_name='date_mod',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_pub',
            new_name='date_pub',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tema',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='forum.Tag'),
        ),
    ]
