# Generated by Django 2.2 on 2020-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='reference',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
