# Generated by Django 2.2.14 on 2020-09-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200910_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
    ]
