# Generated by Django 2.2.14 on 2020-09-08 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pui', models.CharField(default='unknown', max_length=20)),
                ('province', models.CharField(default='unknown', max_length=15)),
                ('grade', models.CharField(default='0', max_length=1)),
                ('phone_number', models.CharField(default='unknown', max_length=9)),
                ('private_number', models.CharField(default='unknown', max_length=14)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='unknown', max_length=9)),
                ('private_number', models.CharField(default='unknown', max_length=14)),
                ('province', models.CharField(default='unknown', max_length=15)),
                ('institute', models.CharField(default='unknown', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
