# Generated by Django 2.2.14 on 2020-09-09 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200908_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='professor',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='Number has to start with (48|47|7|45|42|43|51|41|33|32|31|24|23|22|21|46) characters, where "|" means "or"', regex='^(48|47|7|45|42|43|51|41|33|32|31|24|23|22|21|46)')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=1, validators=[django.core.validators.RegexValidator(regex='[123]{1,1}')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='Number has to start with (48|47|7|45|42|43|51|41|33|32|31|24|23|22|21|46) characters, where "|" means "or"', regex='^(48|47|7|45|42|43|51|41|33|32|31|24|23|22|21|46)')]),
        ),
    ]
