# Generated by Django 2.2.14 on 2020-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200909_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
