# Generated by Django 2.2.14 on 2020-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200916_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='private_number',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='province',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='private_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='province',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
