# Generated by Django 2.2.14 on 2020-09-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_notice_author'),
        ('accounts', '0008_auto_20200916_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Notice'),
        ),
    ]
