# Generated by Django 2.2.14 on 2020-09-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='news',
        ),
    ]
