# Generated by Django 2.2.14 on 2020-09-22 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank='', default='', max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
