# Generated by Django 2.2.14 on 2020-09-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200922_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank='', default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank='', default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='private_number',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
